config:
  publicUri: "http://localhost:9001"
  flags: "disable-registration enable-login-with-password disable-email-verification enable-prepl-server enable-mcp disable-secure-session-cookies"
  postgresql:
    host: "host.docker.internal"
    port: 5432
    username: "penpot"
    password: "penpot"
    database: "penpot"
  redis:
    host: "host.docker.internal"
    port: 6380
    database: "0"
